### ISSUE TITLE
macOS 15 Sequoia | .onChange(of:) value track issue

### ISSUE THREAD

**Issue by mjn2max** [orchetect/MenuBarExtraAccess#13] opened 2024-10-04 03:42 UTC
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

Testing the Library on macOS 15.0 and 15.0.1, tracking the change with .onChange(of:) on MenuBarExtra content (child views) is not correct.

Example:
```swift
struct MenuBarView: View {
    let index: Int
    @Binding var isMenuPresented: Bool
    
    var body: some View {
        VStack(spacing: 40) {
            Image(systemName: "\(index).circle.fill")
                .resizable()
                .foregroundColor(.secondary)
                .frame(width: 80, height: 80)
            Button("Close Menu") {
                isMenuPresented = false
            }
        }
        .padding()
        .frame(width: 250, height: 300)
        .onChange(of: isMenuPresented) { oldValue, newValue in
            print("newValue: \(newValue)")
        }
    }
}
```

---

Noted that the below code is still working fine for macOS 15 & macOS 14, the issue only comes when tracking the value changes on `MenuBarView(...)` and its child views on macOS 15.
```swift
        MenuBarExtra {
            MenuBarView(index: 4, isMenuPresented: $isMenu4Presented)
        } label: {
            Image(systemName: "4.circle.fill")
            Text("Four")
        }
        .menuBarExtraAccess(index: 4, isPresented: $isMenu4Presented)
        .menuBarExtraStyle(.window)
        .onChange(of: isMenu4Presented) { oldValue, newValue in
            print("newValue: \(newValue)")
        }
```

**Comment by orchetect** [comment] 2024-10-04 04:22
`isMenuPresented` isn't meant to be read from your MenuBarExtra's window view (`MenuBarView`).

The view is disappearing in response to the user clicking again on the menubar button to dismiss the window, so the `onChange` inside the window view wouldn't be called. That's not a bug, just the way SwiftUI view lifecycle works.

If you're hoping to trigger code when the window dismisses, you might want to do that from the `App` struct instead of observing this binding in the window view.

`isMenuPresented` is only provided as a binding to `MenuBarView` so that you can manually dismiss the window by setting it to false, which is what the Button is doing there:

```swift
Button("Close Menu") {
    isMenuPresented = false
}
```

**Comment by mjn2max** [comment] 2024-10-04 19:27
Thanks for the quick response. My purpose is to handle some animation each time the MenuBarExtra window is showing. So, I don't think it can be handled from `App` struct.
```
// Example: each child's views A, B, and C have a different animation.
MenuBarView
|------View A (with animation 1)
|------View B (with animation 2)
|------View C (with animation 3)
```

After playing around, I found that I can use `.onAppear()` and `.onDisappear()` to handle it on macOS 15:
```swift
struct MenuBarView: View {
    let index: Int
    @Binding var isMenuPresented: Bool
    @State private var showAnimation: Bool = false

    var body: some View {
        VStack(spacing: 40) {
            Image(systemName: "\(index).circle.fill")
                .resizable()
                .foregroundColor(.secondary)
                .frame(width: 80, height: 80)
            Button("Close Menu") {
                isMenuPresented = false
            }
            .scaleEffect(showAnimation ? 1 : 0.5)
        }
        .padding()
        .frame(width: 250, height: 300)
        .onAppear {
            withAnimation {
                showAnimation = true
            }
        }
        .onDisappear {
            withAnimation {
                showAnimation = false
            }
        }
    }
}
```
---
Noted that I'm trying the same code on macOS 14.7 but it's not working, my observations on different OS versions are:
- macOS 14.7: 
   - `.onChange(of: isMenuPresented)`: work.
   - `.onAppear()` and `.onDisappear()`: not work.
- macOS 15.0: 
   - `.onChange(of: isMenuPresented)`: not work.
   - `.onAppear()` and `.onDisappear()`: work.

**Comment by orchetect** [comment] 2024-10-04 20:05
Oh interesting. Yes I was also thinking of `onDisappear`. I can try that code when I'm back at the office.

In the context of ManuBarExtra closing its window, or just anytime SwiftUI views are being used in a window that closes, I'm not sure what the canonical way is to perform UI action before the window actually disappears.

There's a chance that the behavior changed between macOS 14 and 15 quietly, or it may be a footnote in the release notes, or a bug.

If you need to support at least the last two or more generations of macOS, maybe the solution is to put the `onAppear`/`onDisappear` or `onChange` code into a view modifier that can contain cascading `if #available(macOS ...)` blocks returning whichever code works on each specific platform.

**Comment by orchetect** [comment] 2024-10-05 01:29
I played around with a few solutions but there isn't a simple or canonical way to ensure that an animation plays before a window is closed in this scenario. `onDisappear` technically runs after the view disappears, and SwiftUI is not waiting for it to complete the animation before dismissing the window.

Because the window dismiss event is being fired under the hood as a result of clicking outside of the window, we can't ask it to wait until animation plays and then close.

Ultimately this probably comes down to a SwiftUI issue.

**Comment by mjn2max** [comment] 2024-10-05 02:36
Thanks for all the details. I also think there's the behavior changed between macOS 14 and 15, but can't find any related documents. I'm good with handling it on macOS 15 as previous discussed.
- `.onAppear()`: 
   - Will toggle the `showAnimation = true`
   - We can do whatever animation we want when the MenuBarExtra window opens each time.
- `.onDisappear()`: 
   - Just for resetting `showAnimation = false`, and wait for the next `.onAppear()` to toggle the welcome animations again.
   - I don't think we can handle any exit animation since the MenuBarExtra immediately disappeared.

My work is inspired by how the MenuBarExtra on CleanMyMac app can handle the animation every time it is shown (maybe this app is still using AppKit).

**Comment by orchetect** [comment] 2024-10-05 03:03
Reverting back to `NSStatusItem` instead of `MenuBarExtra` could give you more control over trapping window events and artificially delaying the window from closing so that an animation could complete. You could still do most of the UI with SwiftUI conceivably.

**Closed** 2024-10-05 03:42 UTC
Labels: bug
